package com.example.work;

import android.content.Intent;
import android.os.Bundle;
import android.support.v7.app.AppCompatActivity;
import android.view.View;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;

import java.util.HashMap;
import java.util.Map;

public class AdressTest extends AppCompatActivity {

    Button contButt;
    Button backButt;
    TextView adressTV;
    String name;
    public static String adress;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.adress_test);

        contButt = findViewById(R.id.contButt);
        backButt = findViewById(R.id.backButt);
        adressTV = findViewById(R.id.line2);
        name = MainActivity.custName;

        Map<String, String> map = new HashMap<>();

        map.put("Aarons", "45 Dogwood Ln. Sands Point NY 11050");
        map.put("Ackerman", "22 Morris Ln Oyster Bay Cove NY 11771");
        map.put("Alexander", "545 Caledonia Dr. Dix Hills NY 11746");
        map.put("Alfiero", "49 Derby Greenlawn NY 11740");
        map.put("Altman", "341 Anchorage Woodbury NY 11797");
        map.put("Altman, Russell", "40 Colgate Dr. Woodbury NY 11797");
        map.put("Ambriano", "17 Crane Ct. Lloyd Harbor NY 11743");
        map.put("Amoruso", "20 Westbrook Ct. Greenlawn NY 11740");
        map.put("Amoruso, Nick", "44 Randolf Dr. Dix Hills NY 11746");
        map.put("Angacian", "3 Waylor Laurel Hollow NY 11791");
        map.put("Assael", "3 Polo Ct Woodbury NY ");
        map.put("Atkinson", "53 School Ln. Lloyd Harbor NY 11743");
        map.put("Auerbach", "28 Pinehollow Dr. Greenlawn NY 11740");
        map.put("Axelrod", "19 Ponderosa Melville NY 11746");
        map.put("Axelrod, Ira", "25 Sagamore Syosset NY 11791");
        map.put("Baer", "19 Woodland Drive Sands Point NY 11050");
        map.put("Balemian, Laura", "317 West Neck Rd Lloyd Harbor NY 11743");
        map.put("Bandler", "16 Barkers Pt. Rd. Sand Point NY 11050");
        map.put("Baran", "354 Ridge Ln Millneck NY 11765");
        map.put("Barbour", "738 Remsens Lane Upper Brookville NY 11771");
        map.put("Beal", "10 Little Bull Ct Centerport NY 11721");
        map.put("Beberman", "5 Pelham Ave Sands Point NY 11050");
        map.put("Bell", "27 The Grasslands Woodbury NY 11797");
        map.put("Bell, Nathalie", "4 Cypress Dr. Woodbury NY 11791");
        map.put("Bennett", "97 Buttercup Ln. Huntington NY 11743");
        map.put("Berger, Tricia", "54 Wyoming Huntington Station NY 11746");
        map.put("Beys, Emily", "57 Messenger Lane Sands Point NY 11050");
        map.put("Bez", "4 Half Moon Sands Point NY 11050");
        map.put("Bez, Peter", "23 Richlee Dr. East Northport NY 11731");
        map.put("Bezmalinovic", "2 Buckingham Dr Dix Hills NY 11746");
        map.put("Bhansali", "19 Cobblestone Ct. Centerport NY 11721");
        map.put("Bharara", "1 Windemere Dr. Woodbury NY 11797");
        map.put("Bienenfeld", "17 Meadow Ridge Ln. Old Brookville NY 11545");
        map.put("Bigger", "159 Jennings Rd. Cold Spring Harbor NY 11724");
        map.put("Bill", "115 Browns Rd. Lloyd Harbor NY 11743");
        map.put("Blank, Jamie", "41 Juneau Blvd Woodbury NY 11797");
        map.put("Blank, Sean", "20 Westwood Lane Woodbury NY 11797");
        map.put("Borzooyeh", "13 Clearmeadow Ln. Woodbury NY 11797");
        map.put("Boulukos", "12 Grouse Lane Lloyd Harbor NY 11743");
        map.put("Bozek", "158 East Shore Rd Huntington Bay NY 11743");
        map.put("Brotman", "23 Cherry Lane Syosset NY 11791");
        map.put("Buscaglia", "P.O. Box 242 Syosset NY 11791");
        map.put("Callahan", "378 West Neck Rd.       Lloyd Harbor, NY");
        map.put("Capobianco", "4 Butterfield Ct. Greenlawn NY 11740");
        map.put("Carino", "10 Inlet Dr. Huntington NY 11743");
        map.put("Carino, Sal", "27 Kanes Ln Huntington Bay NY 11743");
        map.put("Carlson", "2 Cobblestone Drive Centerport NY 11721");
        map.put("Chang", "4 Magnolia Woodbury NY 11797");
        map.put("Checo", "11 Hickory Dr. Glen Head NY 11545");
        map.put("Clark", "26 Pinehollow Rd Greenlawn NY 11740");
        map.put("Clegg", "17 Arosa Greenlawn NY 11740");
        map.put("Cohen", "22 Caumsett Farms Ln Woodbury NY 11797");
        map.put("Cohen, Nati", "12 Kodiak Dr. Woodbury NY 11797");
        map.put("Cohen, Phyllis", "22 Yukon Dr. Woodbury NY 11797");
        map.put("Cook", "15 Timberline Dr Huntington NY 11743");
        map.put("Curry", "22 Bartel Dr. Greenlawn NY 11740");
        map.put("Curtis", "120 Buttercup Ln. Huntington NY 11743");
        map.put("Davidson", "2 Equestrian Ct. Huntington NY 11743");
        map.put("De Felice", "7 Pond Field Court Cold Spring Harbor NY 11724");
        map.put("Decapite", "7 Sycamore Woodbury NY 11797");
        map.put("Del Balso", "360  West Neck Rd. Lloyd Harbor NY 11743");
        map.put("Delasandro", "2 Bering Court Woodbury NY 11797");
        map.put("Delia", "3 Kodiak Dr Woodbury NY 11797");
        map.put("Dell", "79 Barkers Point Road Sands Point NY 1050");
        map.put("Dempsey", "79 West Shore Dr. Huntington NY 11743");
        map.put("Denner", "7 Hillcrest Drive Woodbury NY 11797");
        map.put("Deriso, Jamie", "283 Bread and Cheese Hollow Rd Fort Salonga NY 11768");
        map.put("Ding", "22 Elm St Woodbury NY 11797");
        map.put("Dr.  Kalmar", "71 Salem Ridge Dr. Huntington NY 11743");
        map.put("Dreher", "10 Cobblestone Ct. Centerport NY 11721");
        map.put("Duff", "6 Idle Day Drive Centerport NY 11721");
        map.put("Ebert", "53 Windmill Dr. Huntington NY 11743");
        map.put("Ehrlich", "14 Ponderosa Melville NY 11746");
        map.put("Fagin", "1 Plover Ln. Lloyd Harbor NY  11743");
        map.put("Feibl", "325 East Main St. Centerport NY 11721");
        map.put("Feit", "15 Nome Woodbuy NY 11797");
        map.put("Felix", "21 Woodland Rd. Old Brookville NY 11545");
        map.put("Fensterman", "4 Pond Lane                     Sands Point  NY 110501");
        map.put("Ferrara", "11 Polo Court Woodbury NY 11797");
        map.put("Fields", "5 Addison Ln Greenvale NY 11548");
        map.put("Flanagan", "25 Hammond Dr. East Northport NY 11731");
        map.put("Fletcher", "78 McCouns Lane Old Brookville NY 11545-2013");
        map.put("Flowers, Larry", "822 Pulaski Rd Greenlawn NY 11740");
        map.put("Flynn", "18 Brian Lane East Northport NY 11731");
        map.put("Fox ", "24 Westwood Dr. Woodbury NY 11797");
        map.put("Fox, Greta", "4 Sloans Ct Sands Point NY 11050");
        map.put("Friedman", "14 Clearmeadow Lane Woodbury NY 11797");
        map.put("Gaing", "8 Winthrop Dr. Dix Hills NY 11746");
        map.put("Gang", "26 Gabriele Dr. East Norwich NY 11732");
        map.put("Genovesi, Erum", "12 Charles Way Old Brookville NY 115451");
        map.put("Gershowitz", "9 Windemere Dr. Woodbury NY 11797");
        map.put("Ghamar", "40 Keri Way Woodbury NY 11797");
        map.put("Giacobbe", "12 Clearmeadow Ln. Woodbury NY 11797");
        map.put("Godlis", "18 Sousa Dr. Sands Point NY 11050");
        map.put("Goldberg", "17 The Grasslands Woodbury NY 11797");
        map.put("Golden Little Elephant 16", "39 Applegreen Dr. Old Westbury NY 11568");
        map.put("Golden Little Elephant 35", "39 Applegreen Dr. Old Westbury NY 11568");
        map.put("Golden Little Elephant 39", "39 Applegreen Dr Old Westbury NY 11568");
        map.put("Goldsmith, Tom", "32 West Sanders Greenlawn NY 11740");
        map.put("Gordon, Maris", "24 West Creek Farms Rd Sands Point NY 11050");
        map.put("Gottfried", "24 Farmview Rd Port Washington NY 11050");
        map.put("Goyal", "45 Cabriolet Ln Melville NY 11746");
        map.put("Grant", "17 Old House Ln. Sands Point NY 11050-1914");
        map.put("Hafkin", "45 Joyce Lane Woodbury NY 11797");
        map.put("Halal", "29 Bramble Melville NY 11746");
        map.put("Handler", "40 Middle Rd Sands Point NY 11050");
        map.put("Hanover", "18 Woodland Sands Point NY 11050");
        map.put("Haupt", "9 Harbor Hill Rd Huntington Bay NY 11743");
        map.put("Hazan", "4 Orchard Dr. Woodbury NY 11797");
        map.put("Heller", "2 Clearmeadow Ln Woodbury NY 11797");
        map.put("Hentze", "111 High Farms Rd Glen Head NY 11545");
        map.put("Herenstein", "18 Clearmeadow Ct. Woodbury NY 11797");
        map.put("Hirsch", "45 Harbor Lane Roslyn Harbor NY 11576");
        map.put("Hochwald", "95 Buttercup Lane Huntington NY 11743");
        map.put("Honig", "32 Yukon Woodbury NY 11797");
        map.put("Hoover", "759 Remsen's Lane Upper Brookville NY 11771");
        map.put("Horan", "19 Salem Ridge Dr. Huntington NY 11743");
        map.put("Horsch", "26 Larkin St. South Huntington NY 11746");
        map.put("Jackson", "96 Davis Rd Port Washington NY 11050");
        map.put("Jensen", "6 Pond Field Ct. Cold Spring Harbor NY 11724");
        map.put("Kalmar", "5 Little Bull Ct Centerport NY 11721");
        map.put("Kamin, Lewis", "14 Seward Woodbury NY 11797");
        map.put("Kammer", "3 Van Wyck Ln Lloyd Harbor NY 11743");
        map.put("Kaplan", "15 Pironi Court Woodbury NY 11797");
        map.put("Kaplan, Penny", "10 Orchard Ln Old Westbury NY 11568");
        map.put("Kaplan, Steven", "12 Ponderosa Melville NY 11746");
        map.put("Katz", "2 Pond Lane Sands Point NY 11050");
        map.put("Kazanchi", "24 Southwoods Rd. Syosset NY 11791");
        map.put("Kelly, Michael and Mary Beth", "89 Cove Rd Oyster Bay Cove NY 11771");
        map.put("Kerker", "33 Saddle Lane Old Brookville NY 11545");
        map.put("Kern", "4 Clearmeadow Ct. Woodbury NY 11797");
        map.put("Kilcullen, Peter", "10 Deauville Ct Fort Salonga NY 11768");
        map.put("Klein", "2 Hutch Ct. Dix Hills, NY NY 11746");
        map.put("Klipper", "3 Clearmeadow Lane Woodbury NY 11797");
        map.put("Korvar", "24 Shorewood Dr. Sand Point NY 11050");
        map.put("Kramer", "15 Shadow Ln Woodbury NY 11797");
        map.put("Kraulstein", "18 Juneau Blvd Woodbury NY 11797");
        map.put("Laderer", "40 Sunken Orchard Ln. Oyster Bay Cove NY 11771");
        map.put("Lazar", "29 Richbourne Ln Melville NY 11747");
        map.put("Lebowitz", "11 Greenwood Lane Woodbury NY 11797");
        map.put("Leeds, Liz", "140 Jennings Road Cold Spring Harbor NY 11724");
        map.put("Lerner", "9 Clearmeadow Lane Woodbury NY 11797");
        map.put("Levine", "3 Applegreen Old Westbuyr NY 11568");
        map.put("Levitt", "9 Polo Ct Woodbury NY 11797-1123");
        map.put("Lindstrom, Tina", "13 Clearmeadow Ct Woodbury NY 11797");
        map.put("Litman", "5 Bearing Ct Woodbury NY 11797");
        map.put("Locker", "11 Aron Woodbury NY 11797");
        map.put("Loeb", "283 Wheatley Rd. Old Westbury NY 11568");
        map.put("Lucas", "231 Baird Court Woodbury NY 11797");
        map.put("Macarone", "8 Wren Ct Old Brookville NY 11545");
        map.put("Macchiarella", "28 Barrow Ct. Huntington NY 11743");
        map.put("Mahlotra", "7 Hickory Dr Glen Head NY 11545");
        map.put("Maltin", "24 Montfort Syosset NY 11791");
        map.put("Manino", "33 Snowball Ln Cold Spring Harbor NY 11724");
        map.put("Marsalise", "9 Donna Ct Huntington NY 11743");
        map.put("Martin, Tim", "15 Brookhill Lane Huntington NY 11743");
        map.put("McDonagh", "5 Cobblestone Dr. Centerport NY 11721");
        map.put("McTygue", "10 Westfield Dr. Centerport NY 11721");
        map.put("Meirowitz", "80 Wheatley Rd Old Westbury NY 11568");
        map.put("Mevorah, Mindy", "35 Cornwall Ln Sands Point NY 11050");
        map.put("Michaels", "11 Ducharme Ln Greenlawn NY 11740");
        map.put("Michelman", "12 Soundview Ln Sands Point NY 11050-1316");
        map.put("Mohtadi", "16 Clearmeadow Court Woodbury NY 11797");
        map.put("Monaco", "7 Polo Ct. Woodbury NY 11797");
        map.put("Mortarotti", "619 Caledonia Rd. Dix Hills NY 11746");
        map.put("Mosleh", "6 Belaire Ct. Upper Brookville NY 11771");
        map.put("Mosleh, Bita", "1191 Pine Valley Rd Upper Brookville NY 11771");
        map.put("Moslow", "23 Sterling Sands Point NY 11050");
        map.put("Nahas", "8 Pelham Sands Point NY 11050");
        map.put("Nesi", "1356 Ridge Road Laurel Hollow NY 11791");
        map.put("Nierenberg", "14 Plum Beach Pt. Rd Sands Point NY 11050");
        map.put("Nissan", "150 Harbor Acres Sands Point NY 11050");
        map.put("Nordstrom", "30 Fox Meadow Ln Lloyd Harbor NY 11743");
        map.put("O'Connor", "126 West Drive North Massapequa NY 11758");
        map.put("Oliver", "10 Tanyard Ln. Huntington NY 11743");
        map.put("Ospina", "19 Pinehollow Rd Greenlawn NY 11740");
        map.put("Parga", "12 Lancia Dr. East Norwich NY 11791");
        map.put("Park", "4 Turret Woodbury NY 11797");
        map.put("Pasqualone", "21 Topsfield Lane Huntington NY 11743");
        map.put("Passarelli", "9 Birch Ct. Laurel Hollow NY 11771");
        map.put("Pelen Enterprises, Inc.", "17 Green St Huntington NY 11743");
        map.put("Perlmutter", "2 Ariel Ct. Sands Point NY 11050");
        map.put("Pollaci, Joseph", "824 Hilltop Rd Oyster Bay NY 11771");
        map.put("Portanese", "41 Windmill Dr. Huntington NY 11743");
        map.put("Rao", "43 Orchard Ct. Woodbury NY 11797");
        map.put("Rapp", "87 Little Plains Rd Huntington NY 11743");
        map.put("Reynolds", "6 Merry Meeting Lane Lloyd Harbor NY 11743");
        map.put("Rieders", "1 Fairbanks Ct. Woodbury NY 11797");
        map.put("Riley", "18 Woodhull Ct. Northport NY 11768");
        map.put("Rispler", "35 Keri Way Woodbury NY 11797");
        map.put("Robinson", "3 Sloanes Beach Rd Sands Point NY 11050");
        map.put("Roeske", "4 Fiddlers Green Spur Lloyd Neck NY 11743");
        map.put("Romanoff", "25 Banbury Ln Lloyd Harbor NY 11743");
        map.put("Rosenberg", "9 Livengood Ct. Woodbury NY 11797");
        map.put("Ross", "7 Harriman Dr. Sands Point NY 11050");
        map.put("Rueb", "38 Tiffany Ln Oyster Bay Cove NY 11771");
        map.put("Sabatino", "3 Cobblestone Ct. Centerport NY 11721");
        map.put("Samide", "330 Split Rock Rd. Syosset NY 11791");
        map.put("Sangha, Rummy", "402 Woodbury Rd Woodbury NY 11797");
        map.put("Schaefer", "120 W. Creek Farm Rd. Sands Point NY 11050");
        map.put("Schlanger", "56 Saw Mill Rd Cold Spring Harbor NY 11724");
        map.put("Schneider", "19 Westwood Ln. Woodbury NY 11797");
        map.put("Schneider, Michelle", "21 Colgate Ln Woodbury NY 11797");
        map.put("Sciarrino", "20 Wedgewood Ct. Glen Head NY 11545");
        map.put("Serel", "4 Polo Ct. Woodbury NY 11797");
        map.put("Sessa", "12 Woodmont Dr. Melville NY 11746");
        map.put("Shaber", "6 Phaeton Melville NY 11747");
        map.put("Shaber, Debbie", "18 Clearmeadow Ct Woodbury NY 11797");
        map.put("Sharf", "68 McCouns Ln Old Brookville NY 11545");
        map.put("Sher, Gary", "200 Harbor Acres Road Sands Point NY 11050");
        map.put("Sherman, Wendy", "32 Cabriolet Ln Melville NY 11746");
        map.put("Sica", "7 Elm Ct Sands Point NY 11050");
        map.put("Siegel", "28 Sterling Dr. Sands Point NY 11050");
        map.put("Siegel, Andrea", "36 Sousa Sands Point NY 11050");
        map.put("Siegel, Howard", "110 W. Creek Farms Sands Point NY 11050");
        map.put("Simon", "8 Wawapeck Cold Spring Harbor NY 11724");
        map.put("Sirignano", "34 Old Town Ln Halesite NY 11743");
        map.put("Siskind", "2 Shorewood Dr. Sands Point NY 11050");
        map.put("Skolnick", "1 Dogwood Ln Port Washington NY 11050-1109");
        map.put("Smith", "123 East Dr. North Massapequa NY 11758");
        map.put("Solomon", "13 The Grasslands Woodbury NY 11797");
        map.put("Steigman", "3 Sycamore Dr Sands Point NY 11050");
        map.put("Stein", "16 Clearneadow Lane Woodbury NY 11797");
        map.put("Stone", "18 Cornwell Beach Rd Sands Point NY 11050");
        map.put("Su", "7 Greenwood Ln. Woodbury NY 11797");
        map.put("Suneja", "12 Westwood Dr. Huntington NY 11743");
        map.put("Sunshine Pools", "115-6 South 2nd Street Bayshore NY 11706");
        map.put("Talamas, Michael", "28 Wilton Rd Cold Spring Harbor NY 11724");
        map.put("Tallarico", "39 Cromwell Sands Point NY 11050");
        map.put("Taxel", "5 Brook Lane Brookville, NY 11545");
        map.put("Thomas", "12 David Dr. Syosset NY 11791");
        map.put("Tiberio", "12 Oak Point Drive West Bayville NY 11709");
        map.put("Torres", "98 Peach Tree Ln. East Norwich NY 11732");
        map.put("Tsitsoulas", "7 Ponderosa Dr. Melville NY 11747");
        map.put("Vahamonde", "99 Buttercup Ln. Huntington NY 11743");
        map.put("Vandenberg, Nicole", "90 Stillwell Lane Woodbury NY 11797");
        map.put("Wank", "4 Astro Place Dix Hills NY 11746");
        map.put("Wasserman", "14 Wilshire Dr Syosset NY 11791");
        map.put("Wechsler", "38 Orchard Woodbury NY 11797");
        map.put("Weingard", "15 Dogwood Ln Sands Point NY 11050");
        map.put("Weiss, Kevin and Kelly", "49 Arbutus Road Greenlawn NY 11740");
        map.put("Werfel", "331 Anchorage Woodbury NY 11797");
        map.put("Widmer", "10 Salem Ridge Dr. Huntington NY 11743");
        map.put("Wittels", "8 Sterling Dr Sands Point NY 11050");
        map.put("Yan", "18 Linden Lane Old Westbury NY 11568");
        map.put("Zachary", "60 Windmill Drive Huntington NY 11743");
        map.put("Zelentiz", "16 Nome Woodbury NY 11797");
        map.put("Zhang, Donna", "34 Miller Blvd Syosset NY 11791");

        adress = map.get(name);
        String nameAdress = name + adress ;
        adressTV.setText(nameAdress);
        backButt.setOnClickListener(new View.OnClickListener() {

            @Override
            public void onClick(View v) {
                Intent intent = new Intent(AdressTest.this, MainActivity.class);
                startActivity(intent);
            }
        });

        contButt.setOnClickListener(new View.OnClickListener() {

            @Override
            public void onClick(View v) {
                Intent intent = new Intent(AdressTest.this, TaskChoice.class);
                startActivity(intent);
            }
        });
    }
}

